### ISSUE TITLE
Support arrays in generated equals function

### ISSUE THREAD

**Issue by drewhamilton** [drewhamilton/Poko#1]
`toString` and `hashCode` already support this. `data class`es do not, and have an IDE warning about it.

It should be fairly trivial to add support, I'm just not sure if it's a good idea to. It may be unexpected behavior?

**Comment by drewhamilton** [comment]
Deciding not to do this to align as much as possible with data classes.

**Comment by JakeWharton** [comment]
Would you consider making it opt-in with some mechanism? Probably with an annotation like `@ByContent` or `@ContentBased` or something?

**Comment by drewhamilton** [comment]
Yeah I'll consider it. I've held on to a "just do what data classes do except for the one thing" approach for this long, but there's an ever-growing list of interesting features to consider adding so maybe it's time to bite that bullet.

One small challenge is that I currently include the `poko-annotations` dep by default, but allow substituting a custom annotation. If I add more annotations, do I want to allow them to all be customizable, or just drop that feature and force the default annotations dep? Probably the latter but that's a breaking change.

Is Redwood using arrays for performance or another reason? I had the thought of wrapping your arrays in value classes with custom `equals` overrides, but that [isn't supported yet](https://youtrack.jetbrains.com/issue/KT-24874/Support-custom-equals-and-hashCode-for-value-classes) and may be syntactically annoying for your use case.

**Comment by JakeWharton** [comment]
It is for performance, yes. Some of our code runs inside a JS engine where `Array` translates directly to JS's native array whereas `List` is a few Kotlin classes wrapped around an `Array` which adds a lot of copies for things like expansion. Since the only types which interact with these arrays are generated classes, we don't need to worry about the ergonomics as much.

**Comment by drewhamilton** [comment]
So Poko being JVM-only is probably going to block your adoption too? 😬

**Comment by JakeWharton** [comment]
Well, yes. But that's fixable with some PRs!

Wanted to make sure use cases were covered first. Although we only need this for two or _maybe_ three types so writing equals/hashCode manually for them wouldn't have been the end of the world.

**Comment by drewhamilton** [comment]
Kotlin's [decision to avoid special array-handling in data class equals functions](https://blog.jetbrains.com/kotlin/2015/09/feedback-request-limitations-on-data-classes/#Appendix.Comparingarrays) is for JVM-specific reasons. Is it the case that JS native arrays are also not compared by content? Or are the Redwood classes targeting JVM along with JS?

**Comment by JakeWharton** [comment]
> Is it the case that JS native arrays are also not compared by content?

Correct. They mirror the JVM semantics. You must use contentEquals/HashCode/ToString to get the contents rather than the array reference to be used.

> Or are the Redwood classes targeting JVM along with JS?

We target JVM, JS, and many native targets with this code, yes. The efficiency gains are paltry on non-JS platforms.

**Comment by drewhamilton** [comment]
Some notes as I dive deeper – everything I mention here for data classes is also true for Poko classes:
* Data classes do consider content for array-typed properties when computing `hashCode` and `toString`. `equals` is the only one for which array content is ignored.
* Data classes do *not* consider content for `Any`-typed properties that are arrays at runtime when computing `hashCode` and `toString`, so Poko would need to implement its own handling for this.
* Data class handling of `hashCode` and `toString` for arrays is [specifically built in to the IR compiler](https://github.com/JetBrains/kotlin/blob/v1.8.21/compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/IrBuiltIns.kt#L134-L135). Poko would need its own `arrayMemberEqualsSymbol`, and figure out how to map that to the platform-specific `Array.equals` equivalent (I think this is called "lowering"?).
* Need to decide whether to handle nested array types (`Array<Array<T>>`) – that would be `Arrays.deepEquals` on JVM, and the `hashCode` and `toString` implementations would need to be updated to do this too since they currently don't handle nested arrays. Incidentally, `deepEquals` *does* handle Array members even if they are typed `Any`.
* Kotlin's stdlib has `contentEquals` and friends defined [in common code](https://github.com/JetBrains/kotlin/blob/v1.8.21/libraries/stdlib/common/src/generated/_Arrays.kt#L6931-L6939), so mayyybe this can be referenced without any platform-specific handling?

I added #135 to test the current handling of arrays in the sample project.

**Comment by drewhamilton** [comment]
Confirmed that calling common-code stdlib functions from generated IR code is supported, which simplifies this a lot. 🎉

I plan to:
1. Add the new annotation as an experimental API.
2. Implement `contentEquals` for all typed and primitive array types.
3. Handle `contentDeepEquals` for nested array types, updating `hashCode` and `toString` accordingly.
4. Handle `Any` properties that are arrays at runtime.
5. Flesh out the path forward for custom annotation consumers – probably deprecate this feature.

**Comment by drewhamilton** [comment]
Simple array content support is enabled in the latest `0.14.0-SNAPSHOT`, implemented in #141. Not sure if it's possible for Redwood to try it out on just the JVM, otherwise I filed #142 for multiplatform support.
