### ISSUE TITLE
Support multiplatform

### ISSUE THREAD

**Issue by drewhamilton** [drewhamilton/Poko#142]
I never really knew what `data class` did on other platforms, but it sounds like they generate the exact same functions that they do on the JVM. Since Poko is implemented in IR, it should theoretically "just work" for other platform targets.

Haven't done much with Kotlin multiplatform so help and/or PRs are welcome.

Steps to support multiplatform:
- [x] Update annotation module structure to multiplatform
- [x] Update Gradle plugin to apply to all platforms
- [x] Add compiler tests for additional platforms
- [x] Create sample project(s) for additional platform(s)
- [x] Update CI to build and test all platforms
- [x] Determine best use of `implementation` vs. `compileOnly`
- [x] Update CI to publish all platforms

**Comment by JakeWharton** [comment]
You can check off CI as done. Seems to be working: https://oss.sonatype.org/content/repositories/snapshots/dev/drewhamilton/poko/

**Comment by drewhamilton** [comment]
Oh yeah, forgot I switched to the publish plugin that does that for free

**Comment by drewhamilton** [comment]
> should it become supported by all targets

Or if not, we could make it `compileOnly` for non-native targets only, I imagine.

Annoying that end-consumers will have to download the Poko deps for no reason, but I agree it's not a deal-breaker and can be a future optimization. Closing!
