### ISSUE TITLE
Support for all multiplatform targets

### ISSUE THREAD

**Issue by lupuuss** [drewhamilton/Poko#335]
Are there any major blockers for enabling Android Native and Wasm-WASI targets? The lack of support for these targets is currently preventing me from adopting Poko.

**Comment by drewhamilton** [comment]
assertk doesn't currently have Wasm-WASI support, but it [looks like](https://github.com/willowtreeapps/assertk/pull/523) it's coming soon.

I didn't realize Android native was a thing but I don't see a problem with adding it as a target. PRs welcome!
