### ISSUE TITLE
Upgrade to Kotlin 2.0.0 forces users of library to upgrade as well

### ISSUE THREAD

**Issue by paul-dingemans** [drewhamilton/Poko#354]
Ktlint uses the Poko library (version `0.15.0`). With upgrade to Kotlin `2.0.0` in Poko version `0.16.x` [ktlint](https://github.com/pinterest/ktlint) can no longer upgrade to latest version without upgrading ktlint also to version `2.0.0` (see https://github.com/pinterest/ktlint/pull/2676).

Ktlint can not upgrade to Kotlin `2.0.0` as that would force all our users to upgrade as well. Can you please supply an artifact which keep compatible with Kotlin `1.x` as long as Kotlin `1.x` is still supported by Jetbrains?

**Comment by JakeWharton** [comment]
Isn't that what 0.15.0 already is?

You could also use your own annotation instead of the library-provided one which eliminates the transitive dependency problem completely: https://github.com/drewhamilton/Poko?tab=readme-ov-file#annotation.

**Comment by drewhamilton** [comment]
Yep, just stick with Poko 0.15 until you're on Kotlin 2.0.

A custom annotation won't help this; the failure is coming from the compiler plugin using compiler APIs that changed between 1.9 and 2.0.

**Comment by paul-dingemans** [comment]
> Isn't that what 0.15.0 already is?
> 
> You could also use your own annotation instead of the library-provided one which eliminates the transitive dependency problem completely: https://github.com/drewhamilton/Poko?tab=readme-ov-file#annotation.

Oops, I have to admit that I didn't look at the readme at all. I didn't implement `Poko` in `ktlint` myself, so I have limited knowledge of what it does. Assuming that no new version of Kotlin `1.9` will be released, it is clear that no new version of Poko `0.15.x` will be released.

Tnx for quick responses.
