### ISSUE TITLE
Add info about which gpg signing keys will be used for published artifacts

### ISSUE THREAD

**Issue by yogurtearl** [drewhamilton/Poko#401]
### Add info about which gpg signing keys will be used for published artifacts. 

For security purposes, it would be great if you were able to publish details (in the project docs) about gpg public keys that are "valid" for use when verifying signing artifacts uploaded to maven central.

This allows for "out of band" verification of the expected signing key. 

Some examples of other libs publishing their signing keys:

https://square.github.io/okhttp/security/security/#verifying-artifacts

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/KEYS.txt
https://downloads.apache.org/commons/KEYS
https://downloads.apache.org/logging/KEYS

https://github.com/cbeust/jcommander/blob/4b97c3440347bedb79e374408b8f123cf0ff4fd4/SECURITY.md#gpg-signature-validation

**Comment by drewhamilton** [comment]
Is this info sufficient?
```
pub   rsa4096 2020-02-02
      09939C73246B4BA7444CAA453D002DBC5EA9615F
uid   Drew Hamilton <drew.hamilton.0@gmail.com>
sig   3D002DBC5EA9615F 2020-02-02
```

If so I can add it to the readme.

**Comment by yogurtearl** [comment]
Yes, that is sufficient, thanks!
