### ISSUE TITLE
Option to skip individual properties

### ISSUE THREAD

**Issue by drewhamilton** [drewhamilton/Poko#436]
This has now been requested multiple times so I want to make it happen.

It is useful for consumers of Circuit and similar architectures, where the view model is a data class with a view event callback, e.g.:

```kotlin
data class CounterState(
    val count: Int,
    val eventSink: (CounterEvent) -> Unit,
) : CircuitUiState
```

A drawback of this is that as a lambda type, `eventSink` does not implement `equals`, and thus two instances of `CounterState` will never be equals. This can't be fixed with data classes, but it is possible to work around this in Poko by moving the _property_ declaration of `eventSink` out of the constructor:

```kotlin
@Poko class CounterState(
    val count: Int,
    eventSink: (CounterEvent) -> Unit,
) : CircuitUiState {
    val eventSink = eventSink
}
```

But this is annoying to write, and it's not clear why the code is written this way to someone who doesn't already know.

In #182, @ZacSweers proposes a flag in the `@Poko` annotation to exclude lambda types from Poko's function generation. I think this would be too inflexible, and it would require Poko to maintain a list of types that this flag should apply to.

In the same PR, @JakeWharton proposes a new annotation applied to properties that Poko should skip. This is more verbose, but is more flexible and more explicit. The example above is simplified to this:

```kotlin
@Poko class CounterState(
    val count: Int,
    @PokoSkip val eventSink: (CounterEvent) -> Unit,
) : CircuitUiState
```

I'm in favor of this approach. It's pretty trivial to implement, but a few details need to be decided:

- [x] Annotation name: `@PokoSkip`, `@PokoIgnore`, `@Skip`, `@Ignore`, ...? **Answer: Going with `@Skipped` for now, to align naming style and tense with `@ArrayContentBased`.**
- [x] Do prospective consumers of this API need support for a custom annotation class, similar to that for `@Poko`? **Answer: I'll add this if someone asks for it.**
- [x] The skipped property will be omitted from `equals` and `hashCode` completely. How should `toString` behave? My inclination was to omit it, but open to changing that. **Answer: Omitting the skipped property from `toString` until feedback says otherwise.**

**Comment by drewhamilton** [comment]
Answering the questions asked initially:
* Going with `@Skipped` for now, to align naming style and tense with `@ArrayContentBased`.
* Not adding the ability to customize the annotation class now, but I'll add it if someone asks for it.
* Omitting the skipped property from `toString` until feedback says otherwise.

**Comment by ZacSweers** [comment]
Nice! One other thought I had - for the function option, what would you think of an option to automatically skip function properties?

**Comment by drewhamilton** [comment]
Can we see how this per-property annotation does first, and revisit if it proves to really be too verbose?

My initial thoughts are: I don't really want to do this, but if I were convinced I should, then I would want it to be more robust than just `skipFunctionalProperties = true|false`.

**Comment by ZacSweers** [comment]
hmm, what about something like an allowlist of classes or config file similar to compose stability?

**Comment by drewhamilton** [comment]
That would make sense I think. There's a lot of functional types though—`Function1` through `Function20`, I believe—and I've only seem them written with JVM class names. But hopefully there are multiplatform aliases defined for them somewhere, and maybe we could define some shorthand for including all of them.
