### ISSUE TITLE
Publish a Gradle plugin marker

### ISSUE THREAD

**Issue by ZacSweers** [drewhamilton/Poko#54]
Currently no Gradle plugin marker is published here https://repo1.maven.org/maven2/dev/drewhamilton/poko/poko-gradle-plugin/0.8.0/

This makes it impossible to use the plugin without manually including it as a buildscript `classpath` dependency or pointing `pluginManagement` at it.

**Comment by drewhamilton** [comment]
I hadn't heard of this but from skimming the [Gradle docs](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers) it looks straightforward enough.

Want to open a PR? Let me know if so, otherwise I'll get to it this week or next.

**Comment by ZacSweers** [comment]
I don't really know much about it other than just leaving it to the maven publish tool I usually use, so probably better if you do it so I don't change your whole release pipeline ha

**Comment by drewhamilton** [comment]
0.8.1-SNAPSHOT should have this fixed, want to give it a try?

**Comment by drewhamilton** [comment]
Still not working for me. Maybe it's too soon after publishing the snapshot, will take a look again later.

**Comment by drewhamilton** [comment]
Actually I tried it and it seems to work. Will publish 0.8.1 shortly, let me know if it doesn't work for you then.

**Comment by drewhamilton** [comment]
Ugh, the plugin marker's POM is missing details that the snapshots repo didn't care about but Central does. Filed #57 to take a look.
